import type { VetCardProps } from "./vet-card"

// status: "open" (abierto), "closing_soon" (por cerrar), "opening_soon" (abrirá pronto), "closed" (cerrado)
export const featuredVets: (VetCardProps & { id: string })[] = [
  {
    id: "1",
    name: "Clínica Veterinaria San José",
    rating: 4.5,
    reviewCount: 128,
    address: "C. Rosario Castellanos #1211, Albania Alta, 29010 Tuxtla Gutiérrez, Chis.",
    imageUrl: "/images/vets/vet-1.jpg",
    status: "open",
    scheduleTime: "20:00",
    href: "/veterinarias/san-jose",
  },
  {
    id: "2",
    name: "Hospital de Mascotas Tuxtla",
    rating: 4,
    reviewCount: 76,
    address: "29018, Lindavista Shanka, 29018 Tuxtla Gutiérrez, Chis.",
    imageUrl: "/images/vets/vet-2.jpg",
    status: "closing_soon",
    scheduleTime: "18:00",
    href: "/veterinarias/tuxtla",
  },
  {
    id: "3",
    name: "Veterinaria Patitas Felices",
    rating: 5,
    reviewCount: 203,
    address: "Av. 4a. Sur Ote. s/n, San Roque, 29066 Tuxtla Gutiérrez, Chis.",
    imageUrl: "/images/vets/vet-3.jpg",
    status: "closed",
    scheduleTime: "09:00",
    href: "/veterinarias/patitas-felices",
  },
  {
    id: "4",
    name: "Veterinaria Huellitas del Sur",
    rating: 4.2,
    reviewCount: 94,
    address: "9a. Sur Ote. 2549, Bienestar Social, 29077 Tuxtla Gutiérrez, Chis.",
    imageUrl: "/images/vets/vet-4.jpg",
    status: "open",
    scheduleTime: "21:00",
    href: "/veterinarias/huellitas-del-sur",
  },
  {
    id: "5",
    name: "Clínica Veterinaria Xamaipak",
    rating: 4.7,
    reviewCount: 152,
    address: "Calle 15a. Pte. Sur 689, Xamaipak, 29000 Tuxtla Gutiérrez, Chis.",
    imageUrl: "/images/vets/vet-5.jpg",
    status: "opening_soon",
    scheduleTime: "09:00",
    href: "/veterinarias/xamaipak",
  },
  {
    id: "6",
    name: "Veterinaria Centro Zaragoza",
    rating: 3.8,
    reviewCount: 61,
    address: "Calz. Ignacio Zaragoza 1378, Hidalgo, 29000 Tuxtla Gutiérrez, Chis.",
    imageUrl: "/images/vets/vet-6.jpg",
    status: "closing_soon",
    scheduleTime: "19:00",
    href: "/veterinarias/centro-zaragoza",
  },
  {
    id: "7",
    name: "Veterinaria de Prueba",
    rating: 4,
    reviewCount: 10,
    address: "Dirección de prueba, Tuxtla Gutiérrez, Chis.",
    imageUrl: "/images/vets/san-jose.png", // reutiliza cualquier imagen existente
    status: "open",
    scheduleTime: "20:00",
    href: "/veterinarias/prueba",
  },
]