import type { PetCardProps } from "@/components/ui/pet-card"

export const featuredPets: (PetCardProps & { id: string })[] = [
  {
    id: "1",
    name: "Rocky",
    species: "Perro",
    age: "2 años",
    sex: "Macho",
    imageUrl: "/images/pets/perro-1.jpg",
    href: "/adopciones/rocky",
  },
  {
    id: "2",
    name: "Luna",
    species: "Gato",
    age: "1 año",
    sex: "Hembra",
    imageUrl: "/images/pets/gato-1.jpg",
    href: "/adopciones/luna",
  },
  {
    id: "3",
    name: "Max",
    species: "Perro",
    age: "3 años",
    sex: "Macho",
    imageUrl: "/images/pets/perro-2.jpg",
    href: "/adopciones/max",
  },
  {
    id: "4",
    name: "Mia",
    species: "Gato",
    age: "6 meses",
    sex: "Hembra",
    imageUrl: "/images/pets/gato-2.jpg",
    href: "/adopciones/mia",
  },
  {
    id: "5",
    name: "Toby",
    species: "Perro",
    age: "Cachorro",
    sex: "Macho",
    imageUrl: "/images/pets/perro-3.jpg",
    href: "/adopciones/toby",
  },
  {
    id: "6",
    name: "Chispa",
    species: "Gato",
    age: "Adulta",
    sex: "Hembra",
    imageUrl: "/images/pets/gato-3.jpg",
    href: "/adopciones/chispa",
  },
  {
    id: "7",
    name: "Koda",
    species: "Perro",
    age: "Cachorro",
    sex: "Macho",
    imageUrl: "/images/pets/perro-4.jpg",
    href: "/adopciones/koda",
  },
  {
    id: "8",
    name: "Nala",
    species: "Gato",
    age: "Adulta",
    sex: "Hembra",
    imageUrl: "/images/pets/gato-4.jpg",
    href: "/adopciones/nala",
  },
  {
    id: "9",
    name: "Bobby",
    species: "Perro",
    age: "Adulto",
    sex: "Macho",
    imageUrl: "/images/pets/perro-5.jpg",
    href: "/adopciones/bobby",
  },
  {
    id: "10",
    name: "Frida",
    species: "Gato",
    age: "2 años",
    sex: "Hembra",
    imageUrl: "/images/pets/gato-5.jpg",
    href: "/adopciones/frida",
  },
  {
    id: "11",
    name: "Duque",
    species: "Perro",
    age: "4 años",
    sex: "Macho",
    imageUrl: "/images/pets/perro-6.jpg",
    href: "/adopciones/duque",
  },
  {
    id: "12",
    name: "Canela",
    species: "Gato",
    age: "8 meses",
    sex: "Hembra",
    imageUrl: "/images/pets/gato-6.jpg",
    href: "/adopciones/canela",
  },
]